# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 600c2ea64ad8e6be0ec79c8c06152f6d14e9bab97b57418c2c0dc909ca144621adec13c3d2f070371f2e686f2cc5bc1ca6e4a5f61aeb64d0d7197208ab9d862c

test:
  secret_key_base: 6194b7119af4297838db99db4cda803ae608b23db36032af84cb55859eb30803bce44601bf6d404f78b926c8e2ead179680c54bbb54e64825ef41d4a8eb51469

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
